spring:
  application:
    name: company-service
  boot:
    admin:
      client:
        url: http://localhost:7777/


server:
  port: 8303

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

