server:
  port: 8761

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:7777/

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
